services:
  db:
    image: postgres
    container_name: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: newemsdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
    restart: unless-stopped
    volumes:
      - ./postgres_data:/var/lib/postgresql/data

  app:
    build: .
    image: django
    container_name: django
    command: ["python", "manage.py", "runserver", "0.0.0.0:8000"]
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    depends_on:
      - db

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin
    depends_on:
      - db
    restart: unless-stopped

volumes:
  postgres_data:
